### PR TITLE
Update innocent.py

### PR DESCRIPTION
**Pull request by Akai-pop**
lol

### CODE REVIEW

**Comment by Akai-pop** [comment]
1. Your code is broken without explicitly passing intents when constructing Bot.
2. There's no reason for the command check, self_bot internally does the same thing and if that fails so will every command.
3. If the user sends '~hi there' an error will be raised, it is better to ignore it.
4. An error is raised every time the bot tries to ban/kick/whatever as ClientUser is included in guild.members, we want to ignore ourselves.
5. dall is a very messy command as it is, commands group somewhat fixes that.
6. \@everyone is included inside of guild.roles, we should ignore that.
7. Catch if an improper token is passed to run.
8. It is better practice to state what exceptions you are catching in your try/except blocks.

**Comment by kaylynnnn** [comment]
This has made me laugh, I love how this is possibly the worst repo you can do a favour for yet you still do so, I mean more power to you but like this is made with malicious intents 😔.

**Comment by AstroOrbis** [comment]
@Da532 looks all good, no uploading tokens or malicious intent, and fixes some issues

**Review by AstroOrbis — APPROVED** [review]

**Comment by Da532** [comment]
I honestly didn't remember this repo existed as I no longer work on silly little projects such as this, but I've read over this and seems to be in order. Cheers for the **very much needed** amendments.

**Pull request merged**
